# Generated by Django 5.1.2 on 2024-10-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibrosDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Titulo')),
                ('autor', models.CharField(max_length=200, verbose_name='Autor')),
                ('ilustrador', models.CharField(max_length=200, verbose_name='Ilustrador')),
                ('año_salida', models.DateField(verbose_name='Año de salida')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('stock', models.IntegerField(verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': 'Libros',
            },
        ),
    ]
