# Generated by Django 5.1 on 2024-11-15 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libros',
            old_name='Asalida',
            new_name='Año_de_salida',
        ),
    ]
